config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'diaries#index'
  resources :diaries do
    resources :comments, only: %i[new create]
    resources :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
  end
  resources :users
  resources :tasks, except: :show
  resources :infomations

  resources :questions, except: %i[update edit] do
    resources :answers, only: %i[new create]
  end

  get '/atunou', to: 'diaries#atunou_index'

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes
  mount_uploader :avatar, AvatarUploader

  validates :action, presence: true
  validates :date, presence: true

  scope :search, lambda { |search_params|
    return if search_params.blank?

    vegtable_like(search_params[:vegtable])
  }

  scope :vegtable_like, ->(vegtable) { where('vegtable LIKE ?', "%#{vegtable}%") if vegtable.present? }
end

app/models/infomation.rb
# frozen_string_literal: true

class Infomation < ApplicationRecord
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :question, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :icon, IconUploader

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :text, length: { maximum: 100 }

  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_diaries, through: :bookmarks, source: :diary

  def liked_by?(diary_id)
    likes.where(diary_id: diary_id).exists?
  end

  def bookmark(diary)
    bookmarks_diaries << diary
  end

  def unbookmark(diary)
    bookmarks_diaries.delete(diary)
  end

  def bookmark?(diary)
    Bookmark.where(user_id: id, diary_id: diary.id).exists?
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :diary_params

  def create
    Like.create(user_id: current_user.id, diary_id: params[:id])
    redirect_to '/'
  end

  def destroy
    Like.find_by(user_id: current_user.id, diary_id: params[:id]).destroy
    redirect_to '/'
  end

  private

  def diary_params
    @diary = Diary.find(params[:id])
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @questions = Question.all.order('id DESC')
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to '/'
    else
      flash[:alert] = 'タイトル及び内容を記入してください'
      redirect_to action: :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to '/'
  end

  private

  def question_params
    params.require(:question).permit(:title, :question).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @task = Task.new
    @cards = Task.includes(:user).where(user_id: user.find(params[:id]))
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_back fallback_location: @task_url
  end

  private

  def tasks_params
    params.permit(:list, :card, :date).merge(user_id: current_user.id)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/infomations_helper.rb
# frozen_string_literal: true

module InfomationsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/questions/index.html.erb
<div class="question">
  <% @questions.each do |d| %>
  <div class="question_index_title"><%= d.title %></div>
  <div class="question_index_question"><%= d.question %></div>
  <div class="question_index_answer"><%= link_to "熟練農家の回答", question_path(d.id), method: :get %></div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="new_question_box">
  <div class="new_question_content">
    <%= form_with model: @question do |form| %>
      <div class="question_title"><label>質問のタイトルを入力してください<br><%= form.text_field :title, size:"80" %></label></div>
      <div class="question_question"><label>質問内容<br><%= form.text_area :question, size:"80x10" %></label></div>
      <div class="question_submit"><%= form.submit "質問を送る" %></div>
      <%# 投稿に失敗した時(validationで弾かれた時)以下を表示 %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="question">
  <div class="question_index_title"><%= @question.title %></div>
  <div class="question_index_question"><%= @question.question %></div>
  <% if @question.user_id == current_user.id || current_user.admin? %>
    <div class="question_index_delete"><%= link_to "削　　除", question_path(@question.id), method: :delete %></div>
  <% end %>
</div>

<div class="comment_all">
  <% if current_user.admin? %>
    <div id="open">
      <p>Answerを書く</p>
    </div>
    <section id ="modal" class="hidden">
      <%= form_with model: [ @question, @answer] do |form| %>
      <div class="comment_create">
        <p><label>コメントを入力してください <%= form.text_area :answer, size:"80x10" %></label></p>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <div id="close">close</div>
    </section>
    <div id="mask" class="hidden"></div>
  <% end %>

    <% if @answers.exists? %>
      <% @answers.each do |c| %>
        <div class="question_answer"><%= c.answer %></div>
      <% end %>
    <% else %>
      <div class="question_answer"><p>まだ回答はありません。<br>もう少々お待ちください。</p></div>
    <% end %>
</div>
 <%= javascript_pack_tag 'diary/application' %>