config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'diaries#index'
  resources :diaries do
    resources :comments, only: %i[new create]
    resources :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
  end
  resources :users
  resources :tasks, except: :show
  resources :infomations

  resources :questions, except: %i[update edit] do
    resources :answers, only: %i[new create]
  end

  get '/atunou', to: 'diaries#atunou_index'

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes
  mount_uploader :avatar, AvatarUploader

  validates :action, presence: true
  validates :date, presence: true

  scope :search, lambda { |search_params|
    return if search_params.blank?

    vegtable_like(search_params[:vegtable])
  }

  scope :vegtable_like, ->(vegtable) { where('vegtable LIKE ?', "%#{vegtable}%") if vegtable.present? }
end

app/models/infomation.rb
# frozen_string_literal: true

class Infomation < ApplicationRecord
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :question, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :icon, IconUploader

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :text, length: { maximum: 100 }

  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_diaries, through: :bookmarks, source: :diary

  def liked_by?(diary_id)
    likes.where(diary_id: diary_id).exists?
  end

  def bookmark(diary)
    bookmarks_diaries << diary
  end

  def unbookmark(diary)
    bookmarks_diaries.delete(diary)
  end

  def bookmark?(diary)
    Bookmark.where(user_id: id, diary_id: diary.id).exists?
  end
end

app/controllers/diaries_controller.rb
# frozen_string_literal: true

class DiariesController < ApplicationController
  before_action :move_to_index, except: %i[index atunou_index show]

  def index
    @search_params = diary_search_params
    @diaries = Diary.all.order('id DESC').page(params[:page]).per(5).search(@search_params).includes(:user)
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to '/'
    else
      flash[:alert] = '作業項目を入力してください'
      redirect_to action: :new
    end
  end

  def show
    @diary = Diary.find(params[:id])
    @comments = @diary.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
    @diary = Diary.find(params[:id])
  end

  def update
    diary = Diary.find(params[:id])
    diary.update(diary_params)
    redirect_to '/'
  end

  def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy
    redirect_to '/'
  end

  def atunou_index
    user = User.where(admin: true)
    @atunou_diaries = Diary.where(user_id: user.ids).order('id DESC').page(params[:page]).per(5)
  end

  def bookmarks
    @bookmark_diaries = current_user.bookmarks_diaries.includes(:user).order('id DESC').page(params[:page]).per(5)
  end

  private

  def diary_search_params
    params.fetch(:search, {}).permit(:vegtable)
  end

  def diary_params
    params.require(:diary).permit(:vegtable, :action, :image, :text, :date, :avatar).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :diary_params

  def create
    Like.create(user_id: current_user.id, diary_id: params[:id])
    redirect_to '/'
  end

  def destroy
    Like.find_by(user_id: current_user.id, diary_id: params[:id]).destroy
    redirect_to '/'
  end

  private

  def diary_params
    @diary = Diary.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @task = Task.new
    @cards = Task.includes(:user).where(user_id: user.find(params[:id]))
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_back fallback_location: @task_url
  end

  private

  def tasks_params
    params.permit(:list, :card, :date).merge(user_id: current_user.id)
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/infomations_helper.rb
# frozen_string_literal: true

module InfomationsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/diaries/_diaries.html.erb
 <div class="diary_list">
    <div class="diary_item">
      <%= link_to user_path(d.user_id), method: :get do %>    
        <% if d.user.icon? %>
          <%= image_tag d.user.icon.url, class: "icon diary_icon" %>
        <% end %>
      <% end %>
           
        <div class="diary_veg"><%= d.vegtable %></div>
        <div class="diary_action"><%= d.action %></div>
        <div class="diary_date"><%= d.date %></div>
    </div>
      <div class="diary_avatar">
        <%= link_to diary_path(d.id), method: :get do %>
          <% if d.avatar?  %>
            <div class="avatar_avatar"><%= image_tag d.avatar.url  %></div>
          <% else %>
            <div class="avatar_avatar"><%= image_tag 'no_image_logo.png' %></div>
          <% end %>
        <% end %>
        <ul class="diary_next_action">
          <li class="diary_show"><%= link_to "詳　細", diary_path(d.id), method: :get %></li>
          <% if user_signed_in? %>
            <li class="diary_destroy"><%= render 'bookmarks/bookmark_area', diary: d %></li>
            <% if current_user.id == d.user_id || current_user.admin? %>
              <li class="diary_update"><%= link_to "更　新", edit_diary_path(d.id),method: :get %></li>
              <li class="diary_destroy"><%= link_to "削　除", diary_path(d.id), method: :delete %></li>
            <% end %>
            <% if current_user.liked_by?(d.id) %>
              <td><%= link_to destroy_like_path(d), method: :DELETE, remote: true do %> <%= d.likes.count %>
                    <i class="fas fa-heart like"></i>
                  <% end %>
              </td>
            <% else %>
              <td><%= link_to create_like_path(d), method: :POST, remote: true do %> <%= d.likes.count %>
                    <i class="far fa-heart"></i>
                  <% end %>
              </td>
            <% end %>
          <% end %>
        </ul>
      </div>
</div>
 

app/views/diaries/atunou_index.html.erb
 <% @atunou_diaries.each do |d| %>
    <%= render partial:"diaries", locals: { d: d } %>
 <% end %>
 <%= paginate(@atunou_diaries) %> 

app/views/diaries/bookmarks.html.erb
  <tr id="diary_<%= @diaries.id %>">
    <%= render @diaries  %>
  </tr>

 <%= paginate(@bookmark_diaries) %>

app/views/diaries/edit.html.erb
<div class="new_diary_box">
  <section id ="new_modal" class="hidden"> 
    <%= form_with model: @diary do |form| %>
      <div class="diaries_create">
        <p><label>日付を入力してください<br> <%= form.date_select :date, placeholder:"必須" %></label></p>
        <p><label>野菜を入力して下さい<br> <%= form.text_field :vegtable %></label></p>
        <p><label>作業内容を入力して下さい<br> <%= form.text_field :action, placeholder:"※必須" %></label></p>
        <p><label>画像をアップロードして下さい<br> <%= form.file_field :avatar %></label></p>
        <p><label>日記を入力して下さい<br> <%= form.text_area :text, size: "80x10" %></label></p>
        <div class="new_send"><%= form.submit "投稿" %></div>
        <%# 投稿に失敗した時(validationで弾かれた時)以下を表示 %>
        <div class="alert"><%= flash[:alert] %></div>
      </div>
    <% end %>
  </section>
</div>

app/views/diaries/index.html.erb
<div class="index_content">
  <div class="atunou_index"><%= link_to "熟練農家の投稿", atunou_path, method: :get %></div>
  <div class="question_index"><%= link_to "質問一覧", questions_path, method: :get %></div>
</div>
  <div class= "search">
    <%= form_with(scope: :search, url: diaries_path, method: :get, local: true) do |f| %>
        <%= f.text_field :vegtable, value: @search_params[:vegtable],placeholder:"🔍野菜を入力" %>
        <%= f.submit "検索" %>
    <% end %>
  </div>

<div id="new_open">
  <div class="new_question">
    <%= link_to "質問してみる",  new_question_path,method: :get %>
  </div>
  <div class="new_diary">
    <%= link_to "投稿する", new_diary_path,method: :get %>
  </div>
</div>




  <tr id="diary_<%= @diaries.ids %>">
    <%= render partial: 'diaries', collection: @diaries, as: "d"  %>
  </tr>

 <%= paginate(@diaries) %>

app/views/diaries/new.html.erb
<div class="new_diary_box">
  <section id ="new_modal" class="hidden"> 
    <%= form_with model: @diary do |form| %>
      <div class="diaries_create">
        <p><label>日付を入力してください<br> <%= form.date_select :date, placeholder:"必須" %></label></p>
        <p><label>野菜を入力して下さい<br> <%= form.text_field :vegtable %></label></p>
        <p><label>作業内容を入力して下さい<br> <%= form.text_field :action, placeholder:"※必須" %></label></p>
        <p><label>画像をアップロードして下さい<br> <%= form.file_field :avatar %></label></p>
        <p><label>日記を入力して下さい<br> <%= form.text_area :text, size: "80x10" %></label></p>
        <div class="new_send"><%= form.submit "投稿" %></div>
        <%# 投稿に失敗した時(validationで弾かれた時)以下を表示 %>
        <div class="alert"><%= flash[:alert] %></div>
      </div>
    <% end %>
  </section>
</div>

app/views/diaries/search.html.erb
<% @diaries.each do |d| %>
  <%= d.vegtable %>
  <%= d.action %>
  <% if d.avatar?  %>
    <%= image_tag d.avatar.url  %>
  <% end %>
  <%= d.date %>
  <%= link_to "詳細", diary_path(d.id), method: :get %>
  <% if user_signed_in? && current_user.id == d.user_id %>
    <%= link_to "更新", edit_diary_path(d.id),method: :get %>
    <%= link_to "削除", diary_path(d.id), method: :delete %>
  <% end %>
<% end %>

app/views/diaries/show.html.erb
<%# localsの{}内に@diaryを入れるとエラーとなったので,d = @diary に置き換えて値を代入している %>
<% d = @diary %>
  <%= render partial:"/diaries/diaries", locals:{ d: d } %>
  <div class="comment-text"><%= d.text %></div>

<div class="comment_all">
  <% if user_signed_in? %>
    <div id="open">
      <p>コメントを書く</p>
    </div>
    <section id ="modal" class="hidden">
      <%= form_with model: [@diary, @comment] do |form| %>
      <div class="comment_create">
        <p><label>コメントを入力してください <%= form.text_area :comment, size:"80x10" %></label></p>
        <%= form.submit "送信" %>
      </div>
      <% end %>
      <div id="close">close</div>
    </section>
    <div id="mask" class="hidden"></div>
  <% end %>

    <% if @comments %>
      <% @comments.each do |c| %>
        <div class="comment"><%= c.comment %></div>
      <% end %>
    <% end %>
</div>
 <%= javascript_pack_tag 'diary/application' %>