config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'diaries#index'
  resources :diaries do
    resources :comments, only: %i[new create]
    resources :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
  end
  resources :users
  resources :tasks, except: :show
  resources :infomations

  resources :questions, except: %i[update edit] do
    resources :answers, only: %i[new create]
  end

  get '/atunou', to: 'diaries#atunou_index'

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes
  mount_uploader :avatar, AvatarUploader

  validates :action, presence: true
  validates :date, presence: true

  scope :search, lambda { |search_params|
    return if search_params.blank?

    vegtable_like(search_params[:vegtable])
  }

  scope :vegtable_like, ->(vegtable) { where('vegtable LIKE ?', "%#{vegtable}%") if vegtable.present? }
end

app/models/infomation.rb
# frozen_string_literal: true

class Infomation < ApplicationRecord
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :question, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :icon, IconUploader

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :text, length: { maximum: 100 }

  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_diaries, through: :bookmarks, source: :diary

  def liked_by?(diary_id)
    likes.where(diary_id: diary_id).exists?
  end

  def bookmark(diary)
    bookmarks_diaries << diary
  end

  def unbookmark(diary)
    bookmarks_diaries.delete(diary)
  end

  def bookmark?(diary)
    Bookmark.where(user_id: id, diary_id: diary.id).exists?
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :diary_params

  def create
    Like.create(user_id: current_user.id, diary_id: params[:id])
    redirect_to '/'
  end

  def destroy
    Like.find_by(user_id: current_user.id, diary_id: params[:id]).destroy
    redirect_to '/'
  end

  private

  def diary_params
    @diary = Diary.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @task = Task.new
    @cards = Task.includes(:user).where(user_id: user.find(params[:id]))
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.new(tasks_params)
    @task.save
    redirect_back fallback_location: @task_url
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_back fallback_location: @task_url
  end

  private

  def tasks_params
    params.permit(:list, :card, :date).merge(user_id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < ApplicationController
    def new_guest
      user = User.find_or_create_by(email: 'guest@example.com') do |user|
        user.password = SecureRandom.urlsafe_base64
        user.name = 'guest'
      end
      sign_in user
      redirect_to '/', notice: 'ゲストユーザーとしてログインしました'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :move_to_index
  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries.order('id DESC').page(params[:page]).per(5)
    @cards = Task.includes(:user).where(user_id: @user)
  end

  def create
    user = User.find(current_user.id)
    @user = user.create(user_params)
    redirect_to '/'
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    user = User.find(current_user.id)
    @user = user.update(user_params)
    redirect_back fallback_location: '/'
  end

  def index
    @user = User.find(3, 4)
  end

  private

  def user_params
    params.require(:user).permit(:name, :text, :icon)
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/infomations_helper.rb
# frozen_string_literal: true

module InfomationsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users/registrations_helper.rb
# frozen_string_literal: true

module Users
  module RegistrationsHelper
  end
end

app/helpers/users/sessions_helper.rb
# frozen_string_literal: true

module Users
  module SessionsHelper
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/index.html.erb
<div class="user_index_wrapper">
  <div class="user_index_content">
    <% @user.each do |d| %> 
      <% if d.icon? %>
        <div class="user_index_icon"><%= image_tag d.icon.url %></div>
      <% end %>
      <div class="user_index_name"><%= d.name %></div>
      <div class="user_index_text"><%= d.text %></div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
 <div class="mypage">
  <div class="user_show">
    <div class="user_show_icon">
      <% if @user.icon? %>
        <%= image_tag @user.icon.url, class: "icon" %>
      <% end %>
    </div>
    <div class="user_show_name"><%= @user.name %></div>
    <div class="user_show_text"><%= @user.text %></div>

    <div id="user_show_open">
      <p>プロフィールを編集</p>
    </div>
    <section id="user_show_modal" class="hidden">
      <%= form_with model: @user do |form| %>
        <div class="diaries_create">  
          <p><label>名前<br> <%= form.text_field :name %></label></p>
          <p><label>アイコン画像<br> <%= form.file_field :icon %></label></p>
          <p><label>自己紹介<br> <%= form.text_area :text, size: "50x5" %></label></p>
          <%= form.submit "更新" %>
        </div>
        <div id="user_show_close">close</div>
      <% end %>
    </section>
    <div id="user_show_mask" class="hidden"></div>
    <%= javascript_pack_tag 'user/application' %>
  </div>
  <div class="task_diary">
    <div class="task_diary2">
      <div class="task_open active" data-id="diary_all"> 日記を見る</div>
      <div class="task_open" data-id="task_all">タスクを見る</div>
    </div>
    <div class="task_modal active" id="diary_all">
      <% @diaries.each do |d| %>
        <%= render partial:"/diaries/diaries", locals:{ d: d } %>
      <% end %>
    <%= paginate(@diaries) %>
    </div>
    <div class="task">
      <div class="task_modal task_content" id="task_all">
        <div class="task_card" >
        
            <% if @cards != nil %>
              <% @cards.each do |t| %>
                <div class="card_list">
                  <%= t.date %>
                  <%= t.card %>
                  <%= link_to "削除", task_path(t.id), method: :delete %>
                </div>
              <% end %>
            <% end %>
          <div class="card_add">
            
              <p>作業内容を追加</p>
                <%= form_with model: @task, url: {controller: 'tasks', action: 'create'} do |form| %>
                  <div>
                    <p><label>期限<br> <%= form.date_select :date %></label></p>
                    <%= form.text_area :card, size:"25x5", placeholder: "作業内容" %><br>
                    <%= form.submit "作業登録" %>
                  </div>
                <% end %>
        
          </div>
        </div>
      </div>
    </div>
    <%= javascript_pack_tag 'task/application' %>
  </div>
</div>