config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'diaries#index'
  resources :diaries do
    resources :comments, only: %i[new create]
    resources :bookmarks, only: %i[create destroy]
    collection do
      get :bookmarks
    end
  end
  resources :users
  resources :tasks, except: :show
  resources :infomations

  resources :questions, except: %i[update edit] do
    resources :answers, only: %i[new create]
  end

  get '/atunou', to: 'diaries#atunou_index'

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes
  mount_uploader :avatar, AvatarUploader

  validates :action, presence: true
  validates :date, presence: true

  scope :search, lambda { |search_params|
    return if search_params.blank?

    vegtable_like(search_params[:vegtable])
  }

  scope :vegtable_like, ->(vegtable) { where('vegtable LIKE ?', "%#{vegtable}%") if vegtable.present? }
end

app/models/infomation.rb
# frozen_string_literal: true

class Infomation < ApplicationRecord
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :diary
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :question, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :icon, IconUploader

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :text, length: { maximum: 100 }

  has_many :diaries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_diaries, through: :bookmarks, source: :diary

  def liked_by?(diary_id)
    likes.where(diary_id: diary_id).exists?
  end

  def bookmark(diary)
    bookmarks_diaries << diary
  end

  def unbookmark(diary)
    bookmarks_diaries.delete(diary)
  end

  def bookmark?(diary)
    Bookmark.where(user_id: id, diary_id: diary.id).exists?
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/diaries_helper.rb
# frozen_string_literal: true

module DiariesHelper
end

app/helpers/infomations_helper.rb
# frozen_string_literal: true

module InfomationsHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_app.html.erb
<%# レスポンシブ対応用の部分テンプレート %>
<div class="menu_icon" id ="header_open">
   <i class="fas fa-align-justify"></i>
</div>
<div class="overlay">
   <div class="menu_icon" id ="header_close">
      <i class="fas fa-times"></i>
   </div>
   <nav>
      <ul class="header_menu">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="header_menu_list">
                <%= link_to "info作成", new_infomation_path,method: :get  %>
              </li>
            <% end %>
          <li class="header_menu_list">
            <%= link_to "info", infomations_path,method: :get  %>
          </li>
          <li class="header_menu_list">
            <%= link_to "マイページ", user_path(current_user.id),method: :get  %>
          </li>
          <li class="header_menu_list">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <li class="header_menu_list">
            <%= link_to "ブックマーク", bookmarks_diaries_path,method: :get %>
          </li>
          <% else %>
          <li class="header_menu_list guest">
            <%= link_to "ゲストログイン",users_guest_sign_in_path,method: :post, data: { confirm: "ゲストユーザーとしてログインしました" } %>
          </li>
          <li class="header_menu_list">
            <%= link_to "ログイン",new_user_session_path,method: :get %>
          </li>
          <li class="header_menu_list">
            <%= link_to "新規登録",new_user_registration_path,method: :get %>
          </li>
          <% end %>
      </ul>
   </nav>
</div>
<%= javascript_pack_tag 'application/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vegtablelife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
  <div id = "wrapper">
    <header>
      <div class="heading">
        <div class="title">
          <h1>菜園生活<em class="heading_title">　〜すろーらいふ始めませんか〜</em></h1>
          <div class="header_icon"><%= render partial: "/layouts/app" %></div>
        </div>
        <ul class="header_category">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li class="header_list">
                <%= link_to "info作成", new_infomation_path,method: :get  %>
              </li>
            <% end %>
          <li class="header_list header_bookmark">
            <%= link_to  bookmarks_diaries_path,method: :get do %>
              <i class="fas fa-bookmark"></i>
            <% end %>
          </li>
          <li class="header_list">
            <%= link_to "info", infomations_path,method: :get  %>
          </li>
          <li class="header_list my">
            <%= link_to "マイページ", user_path(current_user.id),method: :get  %>
          </li>
          <li class="header_list">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li class="header_list guest">
            <%= link_to "ゲストログイン",users_guest_sign_in_path,method: :post, data: { confirm: "ゲストユーザーとしてログインしました" } %>
          </li>
          <li class="header_list log">
            <%= link_to "ログイン",new_user_session_path,method: :get %>
          </li>
          <li class="header_list">
            <%= link_to "新規登録",new_user_registration_path,method: :get %>
          </li>
          <% end %>
        </ul>
      </div>
    </header>
    <main>
      <%= yield %>
      <li class="header_list modoru">
        <%= link_to "投稿一覧へ",diaries_path,method: :get %>
      </li>
    </main>

    <footer>
      <div class="footer_section">
        <div class="footer_comment">
          <p>Copyright©️2021</p>
        </div>
        <ul class="footer_item">
          <li><a href="https://twitter.com/FivIdPgFeLKuBya" class="footer_list">Twitter</a></li>
          <li><a href="https://qiita.com/kosuke1173" class="footer_list">Qiita</a></li>
        </ul>
      </div> 
    </footer>
  </div>
  </body>
</html>